<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.etoak.et2512</groupId>
    <artifactId>dishes-cloud</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>cloud-common</module>
        <module>cloud-model</module>
        <module>cloud-modules</module>
    </modules>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <!-- 自定义版本号 -->
        <!-- Spring Cloud 2025.0.0 -->
        <cloud.version>2025.0.0</cloud.version>
        <!-- Spring Cloud Alibaba 2025.0.0.0 -->
        <cloud.alibaba.version>2025.0.0.0</cloud.alibaba.version>
        <!-- MyBatis-Plus starter -->
        <mybatis-plus.version>3.5.12</mybatis-plus.version>
        <!-- Druid starter-->
        <druid.version>1.2.28</druid.version>
        <!-- Pagehelper starer -->
        <pagehelper.version>2.1.1</pagehelper.version>
        <!-- hutool-all -->
        <hutool.version>5.8.34</hutool.version>
        <!-- commons-collections4 -->
        <collections4.version>4.5.0</collections4.version>
        <!-- Kaptcha -->
        <kaptcha.version>3.0.0</kaptcha.version>
        <!-- jjwt -->
        <jjwt.version>0.11.2</jjwt.version>
    </properties>
    <!--Spring Boot依赖-->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.11</version>
    </parent>
    <dependencyManagement>
        <dependencies>
            <!-- common-core -->
            <dependency>
                <groupId>com.etoak.et2512</groupId>
                <artifactId>common-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <!-- common-jwt -->
            <dependency>
                <groupId>com.etoak.et2512</groupId>
                <artifactId>common-jwt</artifactId>
                <version>${project.version}</version>
            </dependency>
            <!-- common-web -->
            <dependency>
                <groupId>com.etoak.et2512</groupId>
                <artifactId>common-web</artifactId>
                <version>${project.version}</version>
            </dependency>
            <!-- common-redis -->
            <dependency>
                <groupId>com.etoak.et2512</groupId>
                <artifactId>common-redis</artifactId>
                <version>${project.version}</version>
            </dependency>
            <!-- cloud-model -->
            <dependency>
                <groupId>com.etoak.et2512</groupId>
                <artifactId>cloud-model</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${cloud.alibaba.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid-spring-boot-3-starter</artifactId>
                <version>${druid.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.pagehelper</groupId>
                <artifactId>pagehelper-spring-boot-starter</artifactId>
                <version>${pagehelper.version}</version>
            </dependency>
            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-all</artifactId>
                <version>${hutool.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-collections4</artifactId>
                <version>${collections4.version}</version>
            </dependency>
            <dependency>
                <groupId>com.luamas.kaptcha</groupId>
                <artifactId>kaptcha</artifactId>
                <version>${kaptcha.version}</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-jackson</artifactId>
                <version>${jjwt.version}</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-impl</artifactId>
                <version>${jjwt.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>